services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.dev
    ports:
      - "5089:5089"
    volumes:
      - ./src/backend:/app

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173" # the Vite dev port
    environment:
      - VITE_API_URL=http://localhost:5089
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
