services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile.dev
    ports:
      - "5089:5089"
    volumes:
      - ./src/backend:/app

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4173:5173" # Vite dev port
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    depends_on:
      - backend
