FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

EXPOSE 8080

ENV ASPNETCORE_URLS=http://+:8080
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

CMD ["dotnet", "watch", "run", "--project", "WebServer/WebServer.csproj"]
