// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebServer.Entities;

#nullable disable

namespace WebServer.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260618144028_RemoveTrafficUserAgentReferer")]
    partial class RemoveTrafficUserAgentReferer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("WebServer.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("TrafficId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrafficId");

                    b.ToTable("contacts", (string)null);
                });

            modelBuilder.Entity("WebServer.Entities.EventLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Detail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("TrafficId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TrafficId");

                    b.ToTable("event_logs", (string)null);
                });

            modelBuilder.Entity("WebServer.Entities.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Event")
                        .IsUnique();

                    b.ToTable("events", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Event = "clicked_resume"
                        },
                        new
                        {
                            Id = 2,
                            Event = "clicked_project"
                        },
                        new
                        {
                            Id = 3,
                            Event = "clicked_copy_email"
                        });
                });

            modelBuilder.Entity("WebServer.Entities.TrafficLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.ToTable("traffic_logs", (string)null);
                });

            modelBuilder.Entity("WebServer.Entities.Contact", b =>
                {
                    b.HasOne("WebServer.Entities.TrafficLogs", "Traffic")
                        .WithMany("Contacts")
                        .HasForeignKey("TrafficId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("WebServer.Entities.EventLogs", b =>
                {
                    b.HasOne("WebServer.Entities.Events", "Event")
                        .WithMany("EventLogs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebServer.Entities.TrafficLogs", "Traffic")
                        .WithMany("EventLogs")
                        .HasForeignKey("TrafficId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Event");

                    b.Navigation("Traffic");
                });

            modelBuilder.Entity("WebServer.Entities.Events", b =>
                {
                    b.Navigation("EventLogs");
                });

            modelBuilder.Entity("WebServer.Entities.TrafficLogs", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("EventLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
